blog/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.PostView.as_view()),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('review/<int:pk>/', views.AddComments.as_view(), name='add_comments')]

myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    description = models.TextField('Текст записи')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y')

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'


class Comments(models.Model):
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post
from .form import CommentsForm

class PostView(View):
    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})


class PostDetail(View):
    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComments(View):
    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')

templates/blog/blog.html
{% load static %}
<html>
  <head>
    <title>Блог про бронетехнику</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
  </head>
<body>
<div class="posti">
<a>ПЕХОТНАЯ БРОНИРОВАННАЯ ТЕХНИКА</a>
</div>
    {% for post in post_list %}
          <div class="title">
              <h3><a href="{{ post.id }}">{{ post.title }}</a></h3>
          </div>
          <div class="desc">
              <p>{{ post.description }}</p>
          </div>
    <a href="#"><img src="{{ post.img.url }}" width="300px"></a>
          <div class="author">
              <p>Автор: {{ post.author }}</p>
          </div>
    {% endfor %}
</body>
</html>

templates/blog/blog_detail.html
{% load static %}
<html>
  <head>
    <title>Блог про бронетехнику</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/style2.css' %}" type="text/css" media="all">
  </head>
<body>
<div class="title">
    <h3>{{ post.title }}</h3>
</div>
    <p align="center">
      <a href="#"><img src="{{ post.img.url }}" width="50%"></a>
    </p>
<div class="desc">
    <p>{{ post.description }}</p>
</div>
<div class="author">
    <p>Автор: {{ post.author }}</p>
</div>
 <div class="form-comment">
     <h3>Оставить комментарий</h3>
     <div>
         <form action="{% url 'add_comments' post.id %}" method="post">
             {% csrf_token %}
             <div class="com">
                 <label>Ваш комментарий</label>
                 <textarea name="text_comments"></textarea>
             </div>
             <div class="imya">
                 <label>Ваше имя *</label>
                 <input type="text" name="name">
             </div>
             <div class="email">
                 <label>Ваш Email *</label>
                 <input type="email" name="email">
             </div>
                 <input type="submit">
         </form>
     </div>
     <div>
         {% for comment in post.comments_set.all %}
          <div class="view-comment">
              <h4>{{ comment.name }}</h4>
              <p>{{ comment.text_comments }}</p>
          </div>
         {% endfor %}
     </div>
 </div>
</body>
</html>